---
name: Push
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
  TF_CLOUD_ORGANIZATION: ${{ vars.TF_CLOUD_ORGANIZATION}}
  TF_HOSTNAME: app.terraform.io
  TF_PROJECT: PACCAR Test

jobs:
  retrieve-token:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2

      - name: Get Token
        id: get-token
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          output-credentials: true
          role-to-assume: arn:aws:iam::853670174897:role/github-actions-to-tfc

      - name: Get Workspace ID
        id: get-workspace-id
        uses: dustindortch/actions-tfe-get-workspace-id@v0.1.5
        with:
          organization: ${{ env.TF_CLOUD_ORGANIZATION }}
          token: ${{ env.TF_API_TOKEN}}
          workspace: ${{ vars.TF_WORKSPACE }}

      - name: Set Environment Variables
        id: set-env-vars
        shell: bash
        run: |
          RESPONSE=$(curl -X POST -s -o response.txt -w "%{response_code}" https://app.terraform.io/api/v2/workspaces/${{ steps.get-workspace-id.outputs.workspace_id }}/vars -H 'Content-Type: application/vnd.api+json' -H "Authorization: Bearer ${{ secrets.TF_API_TOKEN }}" -d '{"type": "vars","data": {"attributes": {"key": "AWS_ACCESS_KEY_ID","value": "${{ steps.get-token.outputs.aws-access-key-id }}","category": "env"}}}' 2>&1)
          STATUS=$(cat response.txt | jq '.errors[].status' -r)
          if [ $STATUS == "422" ]; then
            RESPONSE=$(curl -X PATCH -s -o response.txt -w "%{response_code}" https://app.terraform.io/api/v2/workspaces/${{ steps.get-workspace-id.outputs.workspace_id }}/vars/$(curl -s https://app.terraform.io/api/v2/workspaces/${{ steps.get-workspace-id.outputs.workspace_id }}/vars -H "Authorization: Bearer ${{ secrets.TF_API_TOKEN }}" | jq '.data[] | select(.attributes.key == "AWS_ACCESS_KEY_ID") | .id' -r) -H 'Content-Type: application/vnd.api+json' -H "Authorization: Bearer ${{ secrets.TF_API_TOKEN }}" -d '{"type": "vars","data": {"attributes": {"key": "AWS_ACCESS_KEY_ID","value": "${{ steps.get-token.outputs.aws-access-key-id }}","category": "env"}}}' 2>&1)
            cat response.txt
          fi
          # echo "variable_id=$(cat response.txt | jq '.body.data.id' -r)" >> $GITHUB_OUTPUT
          rm response.txt

      # - name: Terraform Cloud Run
      #   id: plan
      #   uses: hashicorp/tfc-workflows-github/actions/create-run@v1.3.0
      #   with:
      #     message: "Run from GitHub Actions"
      #     workspace: ${{ vars.TF_WORKSPACE }}
...