---
name: Push
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
  TF_CLOUD_ORGANIZATION: ${{ vars.TF_CLOUD_ORGANIZATION}}
  TF_HOSTNAME: app.terraform.io
  TF_PROJECT: PACCAR Test
  TFC_AGENT_TOKEN: ${{ secrets.TFC_AGENT_TOKEN }}
  TFC_AGENT_NAME: ${{ secrets.TFC_AGENT_NAME }}

jobs:
  retrieve-token:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Get Token
        id: get-token
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          output-credentials: true
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}

      - name: Install Terraform Cloud Run Agent
        id: agent
        shell: bash
        run: |
          wget https://releases.hashicorp.com/tfc-agent/1.15.1/tfc-agent_1.15.1_linux_amd64.zip
          unzip tfc-agent_1.15.1_linux_amd64.zip
          ./tfc-agent -single &

      - name: Terraform Cloud Run
        id: plan
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.3.0
        with:
          message: "Run from GitHub Actions"
          workspace: ${{ vars.TF_WORKSPACE }}
...